"""Generate the Fabric notebook that creates the operational tables.

  python build_ops_notebook.py
  fab import "fabric duckdb.Workspace/04_ops_ddl.Notebook" -i ../notebooks/04_ops_ddl.Notebook -f
  fab job run "fabric duckdb.Workspace/04_ops_ddl.Notebook"

Why a notebook rather than running the DDL from this machine
------------------------------------------------------------
The Fabric CLI's MSAL cache holds three access tokens (storage, the Fabric API
and ARM) and **no refresh token**, so `acquire_token_silent` cannot mint a token
for the `https://database.windows.net` audience that a SQL connection needs.
There is no local credential to reuse and no DDL-over-REST endpoint for a Fabric
SQL database.

A notebook runs on the capacity, where `notebookutils.credentials.getToken`
issues exactly that audience. It is also reproducible and re-runnable through
`fab job run`, which a local one-off would not be.

The DDL is imported from `ops_db.py` rather than copied, so the local tool and
the notebook cannot drift apart.
"""

import json
import os
import sys

import ops_db

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "notebooks", "04_ops_ddl.Notebook")

WS = "7e0f6e0d-3730-449f-8be6-2beaec28587b"
LAKEHOUSE = "74f54fe9-a2e4-46fc-b7c9-52cb65d752ff"


def md(text):
    lines = text.strip("\n").split("\n")
    return {"cell_type": "markdown",
            "source": [l + "\n" for l in lines[:-1]] + [lines[-1]],
            "metadata": {}}


def code(text):
    lines = text.strip("\n").split("\n")
    return {"cell_type": "code", "execution_count": None, "outputs": [],
            "source": [l + "\n" for l in lines[:-1]] + [lines[-1]],
            "metadata": {}}


def main():
    ddl_literal = json.dumps(ops_db.DDL, indent=4)
    tables_literal = json.dumps(ops_db.TABLES)

    cells = [
        md("""
## Create the operational write-back tables

`fincrime_ops` is a Fabric SQL database, which unlike the mirrored database is
**read-write**. It holds the state the console produces: alert dispositions,
dispute cases and their transitions, KYC actions, and who owns what.

The schema follows `APP_DESIGN.md` section 9. This notebook is generated by
`scripts/build_ops_notebook.py` from the DDL in `scripts/ops_db.py`, so editing
it by hand will be overwritten. Change `ops_db.py` and regenerate.

Every statement guards on existence, so the notebook is safe to re-run.
"""),
        code("""
import struct
import pyodbc
import notebookutils

SERVER   = "%s"
DATABASE = "%s"

# The capacity can issue a token for the SQL audience. A local machine running
# the Fabric CLI cannot, because that CLI's cache holds no refresh token.
raw = notebookutils.credentials.getToken("https://database.windows.net/")
tok = raw.encode("utf-16-le")
packed = struct.pack("<i", len(tok)) + tok

con = pyodbc.connect(
    "Driver={ODBC Driver 18 for SQL Server};Server=" + SERVER +
    ";Database=" + DATABASE + ";Encrypt=yes;TrustServerCertificate=no",
    attrs_before={1256: packed})   # 1256 = SQL_COPT_SS_ACCESS_TOKEN
con.autocommit = True
cur = con.cursor()
print("connected to", DATABASE)
""" % (ops_db.SERVER, ops_db.DATABASE)),

        md("""
### The statements

Two tables carry `_mirror_row_id`. No subset of the 100 business columns is
unique, so the surrogate key added for mirroring is the only stable handle back
to a specific source row. It earns its keep a second time here.

`ops.case_event` is append-only on purpose: regulated casework needs the history
of how a case moved, not just where it ended up, and that history is what makes
the SLA clock auditable.
"""),
        code("DDL = " + ddl_literal + """

for stmt in DDL:
    cur.execute(stmt)
    print("ok:", " ".join(stmt.split())[:78])

print()
print("DDL complete.")"""),

        md("""
### Verify

Counts rather than a bare success message, so a re-run shows the tables are
present and reports what is in them.
"""),
        code("TABLES = " + tables_literal + """

print("%-28s %s" % ("TABLE", "ROWS"))
for t in TABLES:
    cur.execute("SELECT count(*) FROM " + t)
    print("%-28s %d" % (t, cur.fetchone()[0]))

cur.execute(\"\"\"
    SELECT s.name + '.' + t.name AS tbl, c.name AS col, ty.name AS typ
    FROM sys.tables t
    JOIN sys.schemas s ON s.schema_id = t.schema_id
    JOIN sys.columns c ON c.object_id = t.object_id
    JOIN sys.types ty ON ty.user_type_id = c.user_type_id
    WHERE s.name = 'ops'
    ORDER BY tbl, c.column_id
\"\"\")
print()
print("%-26s %-18s %s" % ("TABLE", "COLUMN", "TYPE"))
for r in cur.fetchall():
    print("%-26s %-18s %s" % (r.tbl, r.col, r.typ))

con.close()"""),
    ]

    nb = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "language_info": {"name": "python"},
            "kernelspec": {"name": "synapse_pyspark",
                           "display_name": "Synapse PySpark"},
            "kernel_info": {"name": "synapse_pyspark"},
            "dependencies": {
                "lakehouse": {
                    "default_lakehouse": LAKEHOUSE,
                    "default_lakehouse_name": "fincrime",
                    "default_lakehouse_workspace_id": WS,
                    "known_lakehouses": [{"id": LAKEHOUSE}],
                }
            },
        },
        "cells": cells,
    }

    platform = {
        "$schema": ("https://developer.microsoft.com/json-schemas/fabric/"
                    "gitIntegration/platformProperties/2.0.0/schema.json"),
        "metadata": {"type": "Notebook", "displayName": "04_ops_ddl"},
        "config": {"version": "2.0",
                   "logicalId": "00000000-0000-0000-0000-000000000000"},
    }

    if not os.path.isdir(OUT):
        os.makedirs(OUT)
    with open(os.path.join(OUT, "notebook-content.ipynb"), "w",
              encoding="utf-8") as fh:
        json.dump(nb, fh, indent=1)
        fh.write("\n")
    with open(os.path.join(OUT, ".platform"), "w", encoding="utf-8") as fh:
        json.dump(platform, fh, indent=2)
        fh.write("\n")

    print("wrote %s" % os.path.normpath(OUT))
    print("  %d cells, %d DDL statements" % (len(cells), len(ops_db.DDL)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
