"""End-to-end user acceptance test for the whole pipeline.

  python uat.py                  the full pass, roughly 15 minutes
  python uat.py --skip-source-scan   reuse the last recorded PostgreSQL counts
  python uat.py --no-capacity    local checks only, no capacity job

What it does, in the order the data flows:

  phase 0  the repository: secrets, ignore rules, every script parses, tests
  phase 1  ingestion: PostgreSQL settings, the slot, the replicator, and a
           real change pushed through the WAL and chased into OneLake
  phase 2  transformation: delegated to zz_uat_capacity, which can see the
           lakehouse (generated by build_uat_notebook.py, run here, merged back)
  phase 3  the semantic model: every measure evaluated against Direct Lake,
           reconciled to the verified gold layer, and timed
  phase 4  the application: the report's structure and its binding
  phase 5  the documentation: the numbers the README and BUILD_LOG claim,
           checked against what this run measured

Design rules, learned from the previous pass (BUILD_LOG section 36):

  * a check that cannot run is a FAIL or a SKIP, never a silent pass;
  * nothing is taken from an earlier section on trust, including this file's
    own constants, which is why the source counts are re-measured by default;
  * one failure never hides the next: every check is caught and recorded.

Writes UAT.md and UAT.json at the repository root, and exits non-zero if any
check failed.
"""

import argparse
import io
import json
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))

WS = "7e0f6e0d-3730-449f-8be6-2beaec28587b"
MODEL_ID = "cb8a25d5-76aa-4698-9a25-1e8646809aaa"
REPORT_ID = "16c5f2cc-28ec-42eb-8f57-af8f269af283"
UAT_NB = "zz_uat_capacity"
PROBE_ROW = 12345678          # the designated probe row, marked since section 36

PG = dict(host="localhost", dbname="postgres", user="postgres", password="postgres")

# Fallback source figures, measured 2026-09-19. --skip-source-scan uses these.
LAST_PG_ROWS = 50000001
LAST_PG_DISTINCT = 49406791

SECRET_PATTERNS = [
    (r"(?i)password\s*=\s*['\"][^'\"]{3,}", "a literal password assignment"),
    (r"eyJ[A-Za-z0-9_-]{20,}\.", "what looks like a JWT"),
    # A real tenant name, not the "sulaiman@...onmicrosoft.com" redaction the
    # docs use, which an untethered [a-z0-9.]* would match on its dots alone.
    (r"(?i)@[a-z0-9-]{3,}\.onmicrosoft\.com", "a full account UPN"),
    (r"(?i)client_secret\s*[:=]", "a client secret"),
]
# The password used by every script for a local, throwaway PostgreSQL. It is in
# the README on purpose; the scan must not trip on its own documentation.
SECRET_ALLOW = re.compile(r"postgres[\"']?\s*$|YOUR_PASSWORD|password=\"postgres\"|"
                          r"password='postgres'|\"password\": \"postgres\"")

CHECKS = []


def record(cid, name, state, detail):
    CHECKS.append({"id": cid, "name": name, "state": state, "detail": str(detail)[:600]})
    mark = {"PASS": "PASS", "FAIL": "FAIL", "SKIP": "SKIP"}[state]
    print("  %-5s %-4s %s" % (cid, mark, name))
    if state != "PASS" or os.environ.get("UAT_VERBOSE"):
        print("           %s" % str(detail)[:260])


def check(cid, name, fn):
    """Run one check. An exception is a failure, never the end of the pass."""
    try:
        ok, detail = fn()
    except Exception as e:
        record(cid, name, "FAIL", "%s: %s" % (type(e).__name__, str(e)[:300]))
        return False
    if ok is None:
        record(cid, name, "SKIP", detail)
        return True
    record(cid, name, "PASS" if ok else "FAIL", detail)
    return bool(ok)


# --------------------------------------------------------------------- tools
def fab(*args, timeout=300):
    out = subprocess.run(["fab"] + list(args), capture_output=True, text=True,
                         encoding="utf-8", errors="replace", timeout=timeout)
    body = out.stdout or ""
    i = body.find("{")
    if i < 0:
        return None, (body or out.stderr or "").strip()[:300]
    try:
        return json.loads(body[i:]), None
    except ValueError:
        return None, body[i:][:300]


def api(path, method=None, payload=None, audience=None, timeout=300):
    args = ["api"]
    if audience:
        args += ["-A", audience]
    args.append(path)
    if method:
        args += ["-X", method]
    if payload is not None:
        args += ["-i", json.dumps(payload)]
    d, err = fab(*args, timeout=timeout)
    if err:
        raise RuntimeError(err)
    return d.get("text", d) if isinstance(d, dict) else d


def dax(query, timeout=300):
    body = {"queries": [{"query": query}],
            "serializerSettings": {"includeNulls": True}}
    t = api("groups/%s/datasets/%s/executeQueries" % (WS, MODEL_ID),
            method="post", payload=body, audience="powerbi", timeout=timeout)
    if isinstance(t, dict) and "error" in t:
        raise RuntimeError(json.dumps(t["error"])[:300])
    return t["results"][0]["tables"][0]["rows"]


def pg_connect():
    import psycopg2
    return psycopg2.connect(**PG)


def git(*args):
    out = subprocess.run(["git"] + list(args), cwd=ROOT, capture_output=True,
                         text=True, encoding="utf-8", errors="replace")
    return out.stdout.strip()


# ------------------------------------------------------------------ phase 0
def phase0():
    print("\nPHASE 0  the repository")

    def c_tracked_secrets():
        hits = []
        for rel in git("ls-files").splitlines():
            # Paths leak too. A Fabric SQL database exports one file per
            # database principal, named after the principal, so the account UPN
            # arrived in this public repository as a filename. Contents-only
            # scanning never looked at it.
            for pat, label in SECRET_PATTERNS:
                if re.search(pat, rel):
                    hits.append("%s (in the PATH) %s" % (rel, label))
            path = os.path.join(ROOT, rel)
            if not os.path.isfile(path) or os.path.getsize(path) > 4_000_000:
                continue
            try:
                text = io.open(path, encoding="utf-8", errors="ignore").read()
            except OSError:
                continue
            for pat, label in SECRET_PATTERNS:
                for m in re.finditer(pat, text):
                    line = text[:m.start()].count("\n") + 1
                    frag = text[m.start():m.start() + 90].splitlines()[0]
                    if SECRET_ALLOW.search(frag):
                        continue
                    hits.append("%s:%d %s" % (rel, line, label))
        return not hits, "no secrets in tracked files" if not hits else str(hits[:5])

    def c_ignore_rules():
        names = ["fabric id and pass.md", ".env", "creds.pgpass",
                 "report/FinCrime.Report/.pbi/localSettings.json"]
        bad = []
        for n in names:
            out = subprocess.run(["git", "check-ignore", "-q", n], cwd=ROOT)
            if out.returncode != 0:
                bad.append(n)
        return not bad, "all %d sensitive paths are ignored" % len(names) \
            if not bad else "NOT ignored: %s" % bad

    def c_scripts_parse():
        bad = []
        names = [f for f in sorted(os.listdir(os.path.join(ROOT, "scripts")))
                 if f.endswith(".py")]
        for f in names:
            src = io.open(os.path.join(ROOT, "scripts", f), encoding="utf-8").read()
            try:
                compile(src, f, "exec")
            except SyntaxError as e:
                bad.append("%s line %s: %s" % (f, e.lineno, e.msg))
        return not bad, "all %d scripts parse" % len(names) if not bad else str(bad)

    def c_parser_tests():
        out = subprocess.run([sys.executable, os.path.join(ROOT, "scripts",
                                                           "test_cdc_parser.py")],
                             capture_output=True, text=True, encoding="utf-8",
                             errors="replace", timeout=120)
        tail = (out.stdout or out.stderr or "").strip().splitlines()
        return out.returncode == 0, tail[-1] if tail else "exit %d" % out.returncode

    def c_notebooks_valid():
        base = os.path.join(ROOT, "notebooks")
        bad = []
        for d in sorted(os.listdir(base)):
            p = os.path.join(base, d, "notebook-content.ipynb")
            if not os.path.isfile(p):
                continue
            nb = json.load(io.open(p, encoding="utf-8"))
            ki = nb.get("metadata", {}).get("kernel_info", {})
            if not ki.get("name"):
                bad.append("%s: no kernel_info" % d)
            # %%configure is optional, but Fabric only honours it as cell 0, so
            # one anywhere else is silently ignored and the run lands on 2 vCores.
            for i, c in enumerate(nb["cells"]):
                if "".join(c["source"]).startswith("%%configure") and i != 0:
                    bad.append("%s: configure magic is cell %d, not the first" % (d, i))
            for i, c in enumerate(nb["cells"]):
                if c["cell_type"] != "code":
                    continue
                body = "\n".join(l for l in "".join(c["source"]).splitlines()
                                 if not l.lstrip().startswith("%"))
                try:
                    compile(body, d, "exec")
                except SyntaxError as e:
                    bad.append("%s cell %d: %s" % (d, i, e))
        n = len([d for d in os.listdir(base) if d.endswith(".Notebook")])
        return not bad, "all %d notebooks parse and declare their kernel" % n \
            if not bad else str(bad)

    check("0.1", "no credentials in tracked files", c_tracked_secrets)
    check("0.2", "sensitive paths are covered by .gitignore", c_ignore_rules)
    check("0.3", "every script compiles", c_scripts_parse)
    check("0.4", "the CDC parser unit tests pass", c_parser_tests)
    check("0.5", "every notebook parses and declares its kernel", c_notebooks_valid)


# ------------------------------------------------------------------ phase 1
def phase1(skip_scan):
    print("\nPHASE 1  ingestion, on-prem PostgreSQL to OneLake")
    state = {"pg_rows": LAST_PG_ROWS, "pg_distinct": LAST_PG_DISTINCT,
             "probe_token": "", "probe_row": PROBE_ROW}

    def c_pg_settings():
        cur = pg_connect().cursor()
        cur.execute("SELECT current_setting('wal_level'), current_setting('synchronous_commit')")
        wal, sync = cur.fetchone()
        return (wal == "logical" and sync == "on",
                "wal_level=%s, synchronous_commit=%s" % (wal, sync))

    def c_table_logged():
        cur = pg_connect().cursor()
        cur.execute("SELECT relpersistence FROM pg_class c JOIN pg_namespace n "
                    "ON n.oid=c.relnamespace WHERE n.nspname='landing' AND c.relname='raw_txn'")
        p = cur.fetchone()[0]
        # 'p' is permanent (LOGGED). An UNLOGGED table is never captured by
        # logical replication, so CDC would silently see nothing.
        return p == "p", "relpersistence=%r (p = LOGGED)" % p

    def c_slot():
        cur = pg_connect().cursor()
        cur.execute("SELECT slot_name, plugin, slot_type, active, "
                    "pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)) "
                    "FROM pg_replication_slots WHERE slot_name='fabric_cdc'")
        r = cur.fetchone()
        return bool(r), "slot %s" % (str(r) if r else "fabric_cdc NOT FOUND")

    def c_replicator():
        # Filter on the executable: seven of eight PID matches were shell
        # wrappers last time, which looked like eight competing replicators.
        out = subprocess.run(["powershell", "-NoProfile", "-Command",
                              "(Get-CimInstance Win32_Process -Filter \"Name='python.exe'\" | "
                              "Where-Object { $_.CommandLine -like '*cdc_to_fabric*' } | "
                              "Measure-Object).Count"],
                             capture_output=True, text=True, timeout=120)
        n = (out.stdout or "0").strip()
        return n == "1", "%s genuine python.exe running cdc_to_fabric.py" % n

    def c_mirror_status():
        items = api("workspaces/%s/items" % WS)["value"]
        mid = [i["id"] for i in items if i["type"] == "MirroredDatabase"][0]
        d = api("workspaces/%s/mirroredDatabases/%s/getTablesMirroringStatus" % (WS, mid),
                method="post")
        t = (d.get("data") or [{}])[0]
        state["mirror_id"] = mid
        state["processed_before"] = (t.get("metrics") or {}).get("processedRows")
        return (t.get("status") == "Replicating",
                "%s status=%s processedRows=%s" % (t.get("sourceTableName"),
                                                   t.get("status"),
                                                   state["processed_before"]))

    def c_source_counts():
        if skip_scan:
            return None, ("reusing the recorded figures %d / %d (--skip-source-scan)"
                          % (LAST_PG_ROWS, LAST_PG_DISTINCT))
        cur = pg_connect().cursor()
        t0 = time.time()
        cur.execute("SELECT count(*), count(DISTINCT trim(txn_id)) FROM landing.raw_txn")
        rows, distinct = cur.fetchone()
        state["pg_rows"], state["pg_distinct"] = rows, distinct
        return True, "PostgreSQL holds %s rows, %s distinct txn_id (%.0fs)" % (
            format(rows, ","), format(distinct, ","), time.time() - t0)

    def c_probe_is_safe():
        """The probe row must not have a duplicate twin, or changing it would
        split a dedup group and move the gold row count."""
        cur = pg_connect().cursor()
        cur.execute("SELECT txn_id FROM landing.raw_txn WHERE _mirror_row_id=%s",
                    (PROBE_ROW,))
        r = cur.fetchone()
        if not r:
            return False, "probe row %d is not in the source" % PROBE_ROW
        cur.execute("SELECT count(*) FROM landing.raw_txn WHERE txn_id=%s", (r[0],))
        n = cur.fetchone()[0]
        return n == 1, "probe row %d has txn_id %s, appearing %d time(s)" % (
            PROBE_ROW, r[0], n)

    def c_live_change():
        """The real test of a mirror: change the source, chase it into OneLake."""
        token = "UAT-" + time.strftime("%Y%m%d-%H%M%S", time.gmtime())
        con = pg_connect()
        con.autocommit = True
        cur = con.cursor()
        cur.execute("UPDATE landing.raw_txn SET merchant_name=%s, txn_status=%s "
                    "WHERE _mirror_row_id=%s", (token, "UAT-VERIFIED", PROBE_ROW))
        if cur.rowcount != 1:
            return False, "the UPDATE touched %d rows" % cur.rowcount
        state["probe_token"] = token
        before = state.get("processed_before") or 0
        mid = state["mirror_id"]
        t0 = time.time()
        for _ in range(30):
            time.sleep(15)
            d = api("workspaces/%s/mirroredDatabases/%s/getTablesMirroringStatus"
                    % (WS, mid), method="post")
            now = ((d.get("data") or [{}])[0].get("metrics") or {}).get("processedRows") or 0
            if now > before:
                state["processed_after"] = now
                return True, "set merchant_name=%s; processedRows %s to %s in %.0fs" % (
                    token, format(before, ","), format(now, ","), time.time() - t0)
        return False, "processedRows did not advance past %s within %.0fs" % (
            format(before, ","), time.time() - t0)

    check("1.1", "PostgreSQL is configured for logical replication", c_pg_settings)
    check("1.2", "the landing table is LOGGED, so CDC can see it", c_table_logged)
    check("1.3", "the replication slot exists", c_slot)
    check("1.4", "exactly one replicator process is running", c_replicator)
    check("1.5", "the mirror reports Replicating", c_mirror_status)
    check("1.6", "the source row and key counts, measured now", c_source_counts)
    check("1.7", "the probe row is safe to modify", c_probe_is_safe)
    check("1.8", "a live source change reaches the replication engine", c_live_change)
    return state


# ------------------------------------------------------------------ phase 2
def phase2(state, run_capacity):
    print("\nPHASE 2  transformation, on the capacity")
    if not run_capacity:
        record("2.0", "the capacity half of the pass", "SKIP", "--no-capacity")
        return None

    sys.path.insert(0, HERE)
    import build_uat_notebook

    path = build_uat_notebook.build(pg_rows=state["pg_rows"],
                                    pg_distinct=state["pg_distinct"],
                                    probe_row=state["probe_row"],
                                    probe_token=state["probe_token"])
    out = subprocess.run(["fab", "import",
                          "fabric duckdb.Workspace/%s.Notebook" % UAT_NB,
                          "-i", path, "-f"],
                         capture_output=True, text=True, encoding="utf-8",
                         errors="replace", timeout=600)
    if "imported" not in (out.stdout or "").lower():
        record("2.0", "the capacity notebook imports", "FAIL",
               (out.stdout or out.stderr)[:200])
        return None

    items = api("workspaces/%s/items" % WS)["value"]
    nb_id = [i["id"] for i in items
             if i["displayName"] == UAT_NB and i["type"] == "Notebook"][0]
    start = subprocess.run(["fab", "job", "start",
                            "fabric duckdb.Workspace/%s.Notebook" % UAT_NB],
                           capture_output=True, text=True, encoding="utf-8",
                           errors="replace", timeout=300)
    # fab prints the id two ways and splits them across stdout and stderr, so
    # take the first UUID from either rather than matching one phrasing.
    m = re.search(r"[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}",
                  (start.stdout or "") + (start.stderr or ""))
    if not m:
        record("2.0", "the capacity notebook starts", "FAIL",
               (start.stdout or start.stderr)[:200])
        return None
    job = m.group(0)
    print("           capacity job %s" % job)

    status = None
    for _ in range(40):
        d = api("workspaces/%s/items/%s/jobs/instances/%s" % (WS, nb_id, job))
        status = d.get("status")
        if status in ("Completed", "Failed", "Cancelled", "Deduped"):
            break
        time.sleep(30)
    if status != "Completed":
        record("2.0", "the capacity notebook completes", "FAIL",
               "job %s ended %s: %s" % (job, status, str(d.get("failureReason"))[:200]))
        return None

    dest = os.path.join(ROOT, "uat_capacity.json")
    subprocess.run(["fab", "cp",
                    "fabric duckdb.Workspace/fincrime.Lakehouse/Files/uat_capacity.json",
                    dest.replace("\\", "/"), "-f"],
                   capture_output=True, text=True, timeout=300)
    if not os.path.isfile(dest):
        record("2.0", "the capacity results come back", "FAIL",
               "uat_capacity.json was not produced")
        return None
    cap = json.load(io.open(dest, encoding="utf-8"))
    os.remove(dest)
    for c in cap["checks"]:
        record(c["id"], c["name"], "PASS" if c["ok"] else "FAIL", c["detail"])
    return cap


# ------------------------------------------------------------------ phase 3
def phase3(cap):
    print("\nPHASE 3  the Direct Lake semantic model")

    def measure_names():
        names = []
        base = os.path.join(ROOT, "semantic-model", "definition", "tables")
        for f in sorted(os.listdir(base)):
            for line in io.open(os.path.join(base, f), encoding="utf-8"):
                m = re.match(r"\s*measure '([^']+)'", line)
                if m:
                    names.append(m.group(1))
        return names

    def c_direct_lake():
        base = os.path.join(ROOT, "semantic-model", "definition", "tables")
        modes = set()
        for f in os.listdir(base):
            for line in io.open(os.path.join(base, f), encoding="utf-8"):
                m = re.match(r"\s*mode:\s*(\w+)", line)
                if m:
                    modes.add(m.group(1))
        return modes == {"directLake"}, "partition modes authored: %s" % sorted(modes)

    def c_measures_resolve():
        names = measure_names()
        bad = []
        for n in names:
            try:
                rows = dax('EVALUATE ROW("v", [%s])' % n)
                if not rows:
                    bad.append("%s: no rows" % n)
            except Exception as e:
                bad.append("%s: %s" % (n, str(e)[:80]))
        return not bad, "all %d measures resolve against Direct Lake" % len(names) \
            if not bad else str(bad[:4])

    def c_reconcile():
        """The model must agree with the layer verify.json signed off, or the
        report is showing something the pipeline never produced."""
        if not cap:
            return None, "needs the capacity half"
        v = cap["notes"]["verify"]["tables"]
        rows = dax('EVALUATE ROW("txns", [Transactions], "firings", [Rule Firings], '
                   '"amt", [Total Amount], "alerts", [Alerts Raised])')[0]
        txns, firings = rows["[txns]"], rows["[firings]"]
        ok = (txns == v["fact_transaction"]["rows"]
              and firings == v["fact_alert"]["rows"])
        return ok, ("Transactions %s vs gold %s; Rule Firings %s vs gold %s; "
                    "Total Amount %s; Alerts %s" % (
                        format(txns, ","), format(v["fact_transaction"]["rows"], ","),
                        format(firings, ","), format(v["fact_alert"]["rows"], ","),
                        rows["[amt]"], format(rows["[alerts]"], ",")))

    def c_latency():
        queries = {
            "headline KPIs": 'EVALUATE ROW("t", [Transactions], "a", [Alerts Raised])',
            "overview cube": ('EVALUATE SUMMARIZECOLUMNS(dim_date[yr], dim_date[mth], '
                              'dim_channel[channel], fact_transaction[risk_band], '
                              'fact_transaction[txn_type], "t", [Transactions])'),
            "rules by band": ('EVALUATE SUMMARIZECOLUMNS(fact_transaction[rules_fired], '
                              'fact_transaction[risk_band], "t", [Transactions])'),
        }
        out = {}
        for name, q in queries.items():
            times = []
            for _ in range(3):
                t0 = time.perf_counter()
                rows = dax(q)
                times.append(round(time.perf_counter() - t0, 2))
            out[name] = {"rows": len(rows), "seconds": times}
        warm = max(t["seconds"][-1] for t in out.values())
        # Each timing includes roughly two seconds of `fab` process startup,
        # because every query is a separate CLI invocation. The figure a report
        # user actually sees is measured inside the capacity by 00_README and
        # is about a second; this check is a ceiling, not a benchmark.
        return warm < 20, "%s (each includes ~2s of CLI startup)" % "; ".join(
            "%s %s rows %s" % (k, v["rows"], v["seconds"]) for k, v in out.items())

    check("3.1", "the model is authored as Direct Lake", c_direct_lake)
    check("3.2", "every measure resolves", c_measures_resolve)
    check("3.3", "the model reconciles to the verified gold layer", c_reconcile)
    check("3.4", "report queries answer in seconds, not minutes", c_latency)


# ------------------------------------------------------------------ phase 4
def phase4():
    print("\nPHASE 4  the report")
    rep = os.path.join(ROOT, "report", "FinCrime.Report", "definition")

    def c_pages():
        pages = json.load(io.open(os.path.join(rep, "pages", "pages.json"),
                                  encoding="utf-8"))
        order = pages.get("pageOrder", [])
        on_disk = sorted(d for d in os.listdir(os.path.join(rep, "pages"))
                         if os.path.isdir(os.path.join(rep, "pages", d)))
        ok = (len(order) == 4 and sorted(order) == on_disk
              and order[-1].lower() == "guide")
        return ok, "pageOrder %s, folders %s" % (order, on_disk)

    def c_visuals():
        """Every page carries exactly the content visual and the navigator.
        PBIR renders every folder it finds, so an orphan is a visible defect."""
        bad = []
        for d in sorted(os.listdir(os.path.join(rep, "pages"))):
            vdir = os.path.join(rep, "pages", d, "visuals")
            if not os.path.isdir(vdir):
                continue
            vis = sorted(os.listdir(vdir))
            if len(vis) != 2:
                bad.append("%s has %d visuals: %s" % (d, len(vis), vis))
                continue
            kinds = set()
            for v in vis:
                j = json.load(io.open(os.path.join(vdir, v, "visual.json"),
                                      encoding="utf-8"))
                kinds.add(j.get("visual", {}).get("visualType", "?"))
            if "pageNavigator" not in kinds:
                bad.append("%s has no page navigator: %s" % (d, kinds))
        return not bad, "4 pages, each with a content visual and a navigator" \
            if not bad else str(bad)

    def c_extensions():
        ext = json.load(io.open(os.path.join(rep, "reportExtensions.json"),
                                encoding="utf-8"))
        ents = ext.get("entities", [])
        names = [m["name"] for e in ents for m in e.get("measures", [])]
        entity_ok = all(e["name"] == "fact_transaction" for e in ents)
        return (entity_ok and len(names) == 4,
                "%d report measures on %s" % (len(names),
                                              [e["name"] for e in ents]))

    def c_binding():
        d = json.load(io.open(os.path.join(rep, "..", "definition.pbir"),
                              encoding="utf-8"))
        conn = json.dumps(d.get("datasetReference", {}))
        return ("semanticModelId" in conn,
                "byConnection carries a semanticModelId" if "semanticModelId" in conn
                else conn[:200])

    def c_published():
        items = api("workspaces/%s/items" % WS)["value"]
        r = [i for i in items if i["id"] == REPORT_ID]
        return bool(r), "FinCrime is published in the workspace" if r \
            else "report %s not found" % REPORT_ID

    check("4.1", "the report has four pages, the guide last", c_pages)
    check("4.2", "no orphaned visuals on any page", c_visuals)
    check("4.3", "the report measures bind to a real entity", c_extensions)
    check("4.4", "the report binds to the semantic model by connection", c_binding)
    check("4.5", "the report is published", c_published)


# ------------------------------------------------------------------ phase 5
def phase5(state, cap):
    print("\nPHASE 5  the documentation")
    readme = io.open(os.path.join(ROOT, "README.md"), encoding="utf-8").read()
    buildlog = io.open(os.path.join(ROOT, "BUILD_LOG.md"), encoding="utf-8").read()

    def c_no_dashes():
        bad = []
        for name, text in (("README.md", readme), ("BUILD_LOG.md", buildlog)):
            for ch, label in (("\u2014", "em dash"), ("\u2013", "en dash")):
                if ch in text:
                    bad.append("%s contains a %s" % (name, label))
        return not bad, "no em or en dashes in the docs" if not bad else str(bad)

    def c_logged_instruction():
        """The most dangerous defect an earlier pass found was a README that
        told the reader to load UNLOGGED, which silently breaks CDC. The
        warning has to survive every rewrite of this document."""
        ok = "UNLOGGED" in readme and "LOGGED" in readme
        return ok, ("the README still warns that logical replication never "
                    "captures an UNLOGGED table"
                    if ok else "the UNLOGGED warning has been lost")

    def c_numbers():
        if not cap:
            return None, "needs the capacity half"
        b = cap["notes"]["build"]
        claims = {
            "gold rows": format(b["counts"]["fact_transaction"], ","),
            "duplicates removed": format(b["recon"]["removed"], ","),
        }
        bad = [k for k, v in claims.items() if v not in readme]
        return not bad, ("the README quotes this run's %s" % ", ".join(claims)
                         if not bad else "the README does not quote: %s" % bad)

    def c_readme_is_the_notebook():
        """README.md is the prose of the 00_README notebook, which is the thing
        that runs on the capacity and measures itself. Two copies of the same
        document drift, so this asserts they have not."""
        nb = json.load(io.open(os.path.join(
            ROOT, "notebooks", "00_README.Notebook", "notebook-content.ipynb"),
            encoding="utf-8"))
        md = [("".join(c["source"])).rstrip("\n") for c in nb["cells"]
              if c["cell_type"] == "markdown" and "".join(c["source"]).strip()]
        want = "\n\n".join(md) + "\n"
        if want == readme:
            return True, "README.md is exactly the notebook's %d markdown cells" % len(md)
        return False, ("README.md has drifted from 00_README.Notebook "
                       "(%d vs %d chars); regenerate it from the notebook"
                       % (len(readme), len(want)))

    check("5.1", "no em or en dashes in the documentation", c_no_dashes)
    check("5.2", "the README still warns about UNLOGGED", c_logged_instruction)
    check("5.3", "the README quotes the numbers this run measured", c_numbers)
    check("5.4", "the README is the workspace notebook, not a second copy",
          c_readme_is_the_notebook)


# ------------------------------------------------------------------- report
def write_report(state, cap, started):
    passed = sum(1 for c in CHECKS if c["state"] == "PASS")
    failed = [c for c in CHECKS if c["state"] == "FAIL"]
    skipped = [c for c in CHECKS if c["state"] == "SKIP"]
    stamp = time.strftime("%Y-%m-%d %H:%M:%SZ", time.gmtime(started))

    lines = ["# End-to-end UAT", "",
             "Generated by `scripts/uat.py`. Every line is a check that ran "
             "against the live pipeline, not a claim copied from a document.",
             "",
             "| Run | Value |", "| --- | --- |",
             "| Started | %s |" % stamp,
             "| Duration | %.1f minutes |" % ((time.time() - started) / 60),
             "| Result | **%d passed, %d failed, %d skipped** |"
             % (passed, len(failed), len(skipped)), ""]

    if failed:
        lines += ["## Failures", ""]
        for c in failed:
            lines.append("* **%s %s**: %s" % (c["id"], c["name"], c["detail"]))
        lines.append("")

    groups = [("0", "Repository"), ("1", "Phase 1: ingestion"),
              ("2", "Phase 2: transformation"), ("3", "Phase 3: semantic model"),
              ("4", "Phase 4: application"), ("5", "Documentation")]
    for prefix, title in groups:
        rows = [c for c in CHECKS
                if c["id"].lstrip("P").startswith(prefix)]
        if not rows:
            continue
        lines += ["## %s" % title, "", "| Check | Result | Evidence |",
                  "| --- | --- | --- |"]
        for c in rows:
            detail = c["detail"].replace("|", "\\|").replace("\n", " ")
            lines.append("| %s %s | %s | %s |" % (c["id"], c["name"],
                                                  c["state"], detail))
        lines.append("")

    io.open(os.path.join(ROOT, "UAT.md"), "w", encoding="utf-8",
            newline="\n").write("\n".join(lines) + "\n")
    io.open(os.path.join(ROOT, "UAT.json"), "w", encoding="utf-8",
            newline="\n").write(json.dumps(
                {"ran_at_utc": stamp, "passed": passed, "failed": len(failed),
                 "skipped": len(skipped), "checks": CHECKS,
                 "capacity": (cap or {}).get("notes", {})},
                indent=1, default=str) + "\n")
    return passed, failed, skipped


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-source-scan", action="store_true",
                    help="reuse the recorded PostgreSQL counts instead of a 4 minute scan")
    ap.add_argument("--no-capacity", action="store_true",
                    help="local checks only")
    args = ap.parse_args()

    started = time.time()
    print("END-TO-END UAT  %s" % time.strftime("%Y-%m-%d %H:%M:%SZ", time.gmtime()))
    phase0()
    state = phase1(args.skip_source_scan)
    cap = phase2(state, not args.no_capacity)
    phase3(cap)
    phase4()
    phase5(state, cap)

    passed, failed, skipped = write_report(state, cap, started)
    print("\n%s" % ("-" * 66))
    print("VERDICT: %d passed, %d failed, %d skipped, in %.1f minutes"
          % (passed, len(failed), len(skipped), (time.time() - started) / 60))
    for c in failed:
        print("  FAILED %s %s: %s" % (c["id"], c["name"], c["detail"][:160]))
    print("report written to UAT.md")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
